baseurl = "https://gycwest.com/"
languageCode = "en-us"
title = "GYC West"
theme = "simple1-theme"
publishdir = "../frontend.live"

IgnoreFiles = [
	"\\.kate-swp$",
]

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Ricky Curtice"
	description = "GYC West"

	# Enable Google Analytics by inserting your tracking code
	googleAnalytics = "UA-16290318-6" #"UA-3890335-3" # Pulled off of old web archive https://web.archive.org/web/20160316005751/http://www.gycwest.com/ Not sure who owns this tracker...

	#backendhost = "//10.0.2.13:1313"

	[params.copyright]
		copyrights = [
			"Copyright 2017, Richard Curtice",
		]
