version: '3.7'

networks:
  app:
    name: GYC West Local Dev

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /bin/bash -l
    image: gycwest_frontend
    environment:
      HISTFILE: /home/node/root/.bashcfg/.bash_history
    networks:
      - app
    tty: true
    volumes:
      - bashcfg:/home/node/.bashcfg
      - ..:/app:rw

volumes:
  bashcfg:
